// Writes config.js from SUPABASE_URL and SUPABASE_ANON_KEY.
//
// config.js is gitignored (it is generated, never committed), so every
// deployment has to create it. Vercel runs `npm run build`, which runs this
// script with the project's environment variables; locally, `npm run build`
// reads the same two names from a .env file (see .env.example) when they are
// not already in the environment. Missing values do not fail the build: the
// app then starts in guest mode without cloud sync, and the warning below
// shows up in the build log.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function readDotEnv() {
  const file = resolve(root, '.env');
  if (!existsSync(file)) return {};
  const values = {};
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (!match || line.trim().startsWith('#')) continue;
    values[match[1]] = match[2].replace(/^(['"])(.*)\1$/, '$2');
  }
  return values;
}

// Accept the framework-prefixed names too, in case the variables were created
// for a Next/Vite setup: the prefix only matters to those bundlers.
function pick(name, dotEnv) {
  for (const candidate of [name, `NEXT_PUBLIC_${name}`, `VITE_${name}`, `PUBLIC_${name}`]) {
    const value = (process.env[candidate] || '').trim();
    if (value) return { value, source: `env ${candidate}` };
  }
  const value = (dotEnv[name] || '').trim();
  return value ? { value, source: `.env ${name}` } : { value: '', source: null };
}

const dotEnv = readDotEnv();
const url = pick('SUPABASE_URL', dotEnv);
const anonKey = pick('SUPABASE_ANON_KEY', dotEnv);

const target = resolve(root, 'config.js');
writeFileSync(target, [
  '// Generated by scripts/write-config.mjs — do not edit or commit.',
  `window.SUPABASE_URL = ${JSON.stringify(url.value)};`,
  `window.SUPABASE_ANON_KEY = ${JSON.stringify(anonKey.value)};`,
  ''
].join('\n'));

if (url.value && anonKey.value) {
  console.log(`config.js written for ${new URL(url.value).host} (${url.source}, ${anonKey.source})`);
} else {
  // Names only, never values: this lands in a build log.
  const seen = Object.keys(process.env).filter(k => /SUPABASE/i.test(k)).sort();
  console.warn([
    'WARNING: config.js written with empty values, so sign-in and cloud sync are disabled in this build.',
    `  SUPABASE_URL: ${url.value ? 'set' : 'MISSING'}   SUPABASE_ANON_KEY: ${anonKey.value ? 'set' : 'MISSING'}`,
    `  environment variables containing "SUPABASE": ${seen.length ? seen.join(', ') : 'none'}`,
    `  .env file: ${existsSync(resolve(root, '.env')) ? 'present' : 'absent'}`,
    process.env.VERCEL ? `  Vercel: env=${process.env.VERCEL_ENV || '?'} branch=${process.env.VERCEL_GIT_COMMIT_REF || '?'} project=${process.env.VERCEL_PROJECT_PRODUCTION_URL || '?'}` : '  Vercel: not detected',
  ].join('\n'));
}
