// Writes config.js from SUPABASE_URL and SUPABASE_ANON_KEY.
//
// config.js is gitignored (it is generated, never committed), so every
// deployment has to create it. Vercel runs `npm run build`, which runs this
// script with the project's environment variables; locally, `npm run build`
// reads the same two names from a .env file (see .env.example) when they are
// not already in the environment. Missing values do not fail the build: the
// app then starts in guest mode without cloud sync, and the warning below
// shows up in the build log.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function readDotEnv() {
  const file = resolve(root, '.env');
  if (!existsSync(file)) return {};
  const values = {};
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (!match || line.trim().startsWith('#')) continue;
    values[match[1]] = match[2].replace(/^(['"])(.*)\1$/, '$2');
  }
  return values;
}

const dotEnv = readDotEnv();
const url = process.env.SUPABASE_URL || dotEnv.SUPABASE_URL || '';
const anonKey = process.env.SUPABASE_ANON_KEY || dotEnv.SUPABASE_ANON_KEY || '';

const target = resolve(root, 'config.js');
writeFileSync(target, [
  '// Generated by scripts/write-config.mjs — do not edit or commit.',
  `window.SUPABASE_URL = ${JSON.stringify(url)};`,
  `window.SUPABASE_ANON_KEY = ${JSON.stringify(anonKey)};`,
  ''
].join('\n'));

if (url && anonKey) {
  console.log(`config.js written for ${new URL(url).host}`);
} else {
  console.warn('WARNING: SUPABASE_URL and/or SUPABASE_ANON_KEY are not set; config.js written with empty values, so sign-in and cloud sync are disabled in this build.');
}
